Исправлены опечатки
lounres/SPbU-MCS-2020-M-lecture-notes pull request #1
Opened 2020-09-26 12:44 UTC by gtivansan

С пробелами - косяк. Их моя среда поизменяла.

2020-09-26 12:45 UTC, gtivansan commented
Могу попробовать без стирания лишних пробелов сделать.

2020-09-26 15:55 UTC, lounres commented on МатАн/MA.tex
> +    \begin{definition}\
Конкретно этот пробел является частью команды `\ `, делающей пробельный символ.

P.S. Она нужна, чтобы первая строка была непуста, и тем самым первый пункт последующего списка писался на следующей строке, а не сразу после "Определение 15.". Такие костыли...

2020-09-26 15:57 UTC, lounres requested changes
Всё круто, исчезнувшие отступы меня не пугают, но есть другой момент:

2020-09-26 15:57 UTC, lounres commented on МатАн/MA.tex
> +    \begin{definition}\
Конкретно этот пробел является частью команды `\ `, делающей пробельный символ.

P.S. Она нужна, чтобы первая строка была непуста, и тем самым первый пункт последующего списка писался на следующей строке, а не сразу после "Определение 15.". Такие костыли...

2020-09-26 15:57 UTC, lounres commented on МатАн/MA.tex
> +    \begin{corollary*}\
Та же история.

2020-09-26 15:57 UTC, lounres commented on МатАн/MA.tex
> +    \begin{definition}\
Та же история.

2020-11-03 19:58 UTC, lounres commented
Опечатки другими коммитами.

2020-11-03 19:58 UTC, closed without merging